apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/muthappamk1/k3s-cluster
    targetRevision: HEAD
    path: apps/k3s-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
