apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k3s-app
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: k3s-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k3s-app
            port:
              number: 5000
